# Generated by Django 4.0 on 2021-12-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iothome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='mobile',
        ),
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(default='sabarish', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
